### ISSUE TITLE
Add PIC32MX compatibility

### ISSUE THREAD

**Issue by sampaisenpai** [adafruit/Adafruit-PN532#31]
Is there an existing (or a work in progress) of this library for Microchip PIC32MX? I was redirected here by a page on platformio http://platformio.org/lib/show/29/Adafruit-PN532/examples where it said the library was compatible with pic32 but in the readme it doesn't include it.. Is the readme not updated or is it the page on platformio? thank you for clearing this out :)

**Comment by microbuilder** [comment]
Not to my knowledge. Closing this for now.
