### ISSUE TITLE
Missing implementations of inListPassiveTarget and inDataExchange

### ISSUE THREAD

**Issue by djMax** [adafruit/Adafruit-PN532#5]
Would be very useful to have these so it's easier to move from I2C to SPI.

**Comment by tdicola** [comment]
Thanks for raising the issue and apologies it took a little while to be reviewed.  This should be fixed now with this commit to merge the two libraries: https://github.com/adafruit/Adafruit-PN532/commit/e1aa0c2b6c6082fdbd18c5952d7aa0fd3d4791e2  Thanks again for suggesting the fix!
