### ISSUE TITLE
SPI Multiple Slaves CS Issue

### ISSUE THREAD

**Issue by ivoh95** [adafruit/Adafruit-PN532#61]
Multiple SPI slaves is not working correctly, the SS pin is not set high upon defining of each NFC instance and multiple slaves get selected since the pin is low by default. 

To fix this a digitalWrite(_ss, HIGH);  needs to be added after lines 182 and lines 137 in the .ccp file 

The bug has been tested and confirmed on an arduino mega and arduino mega. And the fix has been tested to work with 6 nfc readers.

**Comment by ladyada** [comment]
nice - can you submit a PR? thank you :)
