### ISSUE TITLE
Weird delays in the source code. 

### ISSUE THREAD

**Issue by rewolff** [adafruit/Adafruit-PN532#68]
Hi, 
The library has a bunch of "weird' delays  in places where you don't expect them. I've ported the library for my own use, and thought I'd optimize the delays a bit. (thinking I would eliminate most of them... boy was I wrong). 

i've given each of the delays in my code an identifier and use that identifier to index  the "delays" array. If there is a nonzero number there, I wait for that number of tenth-of-a-milisecond-s. 

While debugging I did add a few extra delays that were not there, so it'll be a bit of work for you to find the precise relationship between my delay identifiers and your code. But "isready_T1" and  :"ISREADY_T2" are obviously both from the "isready" function. As both numbers ended up zero after my optimization of the delays, any delay in isready can be removed. Readdata t1 are the after-CS-delay, the before-get-the-data- and the after-get-the-data delays. Last one is zero as expected. etc. 

```
/*
enum delays_id { ISREADY_T1, ISREADY_T2, READDATA_T1, READDATA_T2, READDATA_T3, 
		 WAITREADY, WRITECMD_T1, WRITECMD_T2, INIT_T1, INIT_T2, INIT_T3, 
		 // Keep this last 
		 LAST_DELAY_ID};
*/

int delays[MAXDELAYS] = {0, 0, 4, 10, 0, 
			 10, 10, 0, 2000, 0, 0};
```

**Comment by caternuson** [comment]
See datasheet and other documentation for timing requirements. Although others are possibly determined by trial and error.

If there is an actual issue resulting from the delays, please provide more information and an example sketch to demonstrate. Closing for now, but can reopen if turns into actual issue.

**Comment by rewolff** [comment]
Yeah. My conclusion was that most of the delays in the code were not documented in the datasheet. 
And I created infrastructure in my own code to be able to quickly test different delays. That way I was able to quickly find the minimal delays that worked. My timings are much tighter than yours. 

But if you don't want to use my work on this, you're welcome to ignore it.
