### ISSUE TITLE
PN532DEBUGPRINT.println("TIMEOUT!");

### ISSUE THREAD

**Issue by ARedkov** [adafruit/Adafruit-PN532#70]
Сообщение "TIMEOUT!" выводится каждый раз при инициализации в фукнции nfc.readPassiveTargetID(PN532_MIFARE_ISO14443A, uid, &uidLength, 1000);

Необходимо добавить условие, что только при DEBUG MODE будет выводится данное сообщение

if (timer > timeout) {

#ifdef MIFAREDEBUG
        PN532DEBUGPRINT.println("TIMEOUT!");
 #endif
        return false;
      }

**Comment by ladyada** [comment]
fixed in 1.2.0+
