### ISSUE TITLE
Works on SAMD21

### ISSUE THREAD

**Issue by vmsh0** [adafruit/Adafruit-PN532#86]
Hello,

The library works on SAMD21 (M0 Pro) using I2C, so the README should probably be corrected :)

- R

**Comment by smalesevic** [comment]
Can the README include compatibility with Arduino Uno Wifi Rev2 (ATmega4809)?

**Comment by caternuson** [comment]
The compatibility table is going to be removed. While generally useful, these are near impossible to maintain and keep up to date.
