### ISSUE TITLE
 Arduino + PN532 with chip tsd9471 not work with emv card

### ISSUE THREAD

**Issue by chiffacff** [adafruit/Adafruit-PN532#90]
hello. A I have 2 PN532 device first with chip tsd9471 and second with tsd4331. I try to read EMV bankcard, and have some trouble.
device with tsd4331 read fine, and device with tsd9471 always return fail on nfc.inListPassiveTarget();  with card but work fine with ApplePay.

Please help, how to make it universal? Thanks!

**Comment by caternuson** [comment]
Please post in the forums with photos of your setup:
https://forums.adafruit.com/
