### ISSUE TITLE
Use a mobile phone instead of a card

### ISSUE THREAD

**Issue by 6000850** [adafruit/Adafruit-PN532#91]
Hi, I am using the pn532 module
My wiring and connection to the module is through the software serial
When I hold the mobile phone in front of this module, it displays a different UID each time.
I want to use a mobile phone instead of a card and each phone has a unique ID so I can identify who this mobile phone is for.

My board : wemos d1 mini

please guide me

**Comment by tmckenna-1** [comment]
Can you post your code?

**Comment by braysonjohn148** [comment]
Did it work? I have an Android phone HCE it keeps giving a random ID how can I know the user/device which has tapped?

**Comment by caternuson** [comment]
Need to see full code for sketch being run.

**Comment by caternuson** [comment]
Closing for now. Can reopen if full example sketch code can be provided to demonstrate the issue.
